### ISSUE TITLE
graphs plz

### ISSUE THREAD

**Issue by dennisyuan** [bradysalz/team-pls#2]
line plots make no sense. Would rather see all plots as histograms or bar graphs. Wins would be binned into 2 bars: wins and losses. Kills or Deaths could be binned into # of kills or deaths per game. Samples too sparse to make any sense of time series data.

**Comment by inkounter** [comment]
It may be worth keeping time series graphing for the future, when there are more samples.

**Comment by bradysalz** [comment]
Histograms added loose bar charts. Closing.
