### ISSUE TITLE
bar graph percent

### ISSUE THREAD

**Issue by dennisyuan** [bradysalz/team-pls#3]
Bar graphs y axis should be % of games, not # of games. More games played shouldn't cause arbitrarily taller bar graphs.

**Comment by kashev** [comment]
It should probably be a toggle? One would want to know often who plays with team, and if one team is more frequent than no-team.

**Comment by dennisyuan** [comment]
maybe that should be a separate feature, not a toggle. A page for stats on number of games played with team vs without team. Still think y axis of current bar graphs should be changed to % of games.

**Comment by bradysalz** [comment]
Pushed on the bar graph page.
